config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "home" => "static_pages#home"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :lessons
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :categories, only: [:index, :show]
  resources :words, only: [:index]
  resources :lessons
  namespace :admin do
    root "users#index"
    resources :users, only: [:destroy, :index, :update]
    resources :words
    resources :categories
  end

end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :word_answers, dependent: :destroy
  has_many :results
  has_many :lessons, through: :results
  validates :content, :category_id, presence: true
  scope :filter_by_category, -> category_id do
    where category_id: category_id if category_id.present?
  end

  scope :show_all, -> user_id {}

  scope :learned, -> user_id do
    joins(:lessons).distinct.
      where(lessons: {is_complete: true, user_id: user_id})
  end

  scope :unlearned, -> user_id do
    where.not id: Word.learned(user_id)
  end

  accepts_nested_attributes_for :word_answers,
    reject_if: proc {|attributes| attributes["content"].blank?},
    allow_destroy: true
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user, :verify_admin, :load_categories
  before_action :load_word, only: [:edit, :update, :destroy]

  def index
    @words = Word.filter_by_category(params[:category_id]).
      paginate page: params[:page], per_page: Settings.per_page
  end

  def new
    @word = Word.new
    4.times{@word.word_answers.build}
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t ".success", word: @word.content
      redirect_to admin_words_url
    else
      4.times{@word.word_answers.build}
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_params
      flash[:success] = t ".success", word: @word.content
      redirect_to admin_words_url
    else
      flash[:danger] = t ".failed"
      render :edit
   end
  end

  def destroy
    if @word.destroy
      flash[:success] = t ".message_scucess", word: @word.content
      redirect_to admin_words_url
    end
  end

  private
  def word_params
    params.require(:word).permit :content, :category_id,
      word_answers_attributes: [:id, :content, :correct_answer]
  end

  def load_categories
    @categories = Category.all
  end

  def load_word
    @word = Word.find_by id: params[:id]
    unless @word
      flash[:danger] = t ".not_found"
      redirect_to admin_root_url
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @categories = Category.all
    filter_type = params[:word_filter] || Settings.word_filter.last
    @words = Word.send(filter_type, current_user.id).
      filter_by_category(params[:category_id]).
      paginate page: params[:page], per_page: Settings.per_page
  end
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div>
    <%= f.label :content %>
    <%= f.text_field :content, class: "form-control" %>
  </div>
  <div class="categories_select">
    <%= f.label :category_id %>
    <%= f.select :category_id,
      options_for_select(@categories.map{|c| [c.conten, c.id]}),
      {}, class: "form-control" %>
  </div>
  <div class="word_answer">
    <h3><%= t ".answers" %></h3>
    <%= f.fields_for :word_answers do |builder| %>
      <%= builder.label :content, t(".word_answer") %>
      <%= builder.text_field :content, size: Settings.size_text_field %>
      <%= builder.label :correct_answer, t(".correct_answer") %>
      <%= builder.check_box :correct_answer, class: "is_correct_answer" %>
      <br>
    <% end %>
  </div>
  <div class= "button_action" >
    <%= f.submit class: "my_btn" %>
  </div>
<% end %>

app/views/admin/words/_word.html.erb
<tr>
  <td class="col-md-2" >
    <div class="word">
      <%= word.content %>
    </div>
  </td>
  <td class="col-md-3">
   <div class="answer">
    <ul>
      <% word.word_answers.each do |answer| %>
        <li class="answer-<%= answer.correct_answer%>">
          <%= answer.content %>
        </li>
      <% end %>
    </ul>
   </div>
  </td>
  <td class="col-md-5">
    <div class="categories">
      <%= word.category.conten %>
    </div>
  </td>
  <td class="col-md-2">
    <div class="button_action center">
      <%= link_to edit_admin_word_path(word), "data-toggle": "tooltip",
        title: t("tooltip_edit") do  %>
        <span class="glyphicon glyphicon-pencil"></span>
      <% end %>
      <%= link_to [:admin, word], "data-toggle": "tooltip",
        title: t("tooltip_delete"), method: :delete do  %>
          <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    </div>
  </td>
</tr>

app/views/admin/words/edit.html.erb

<div class="row">
  <h1><%= t ".title" %></h1>
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/words/index.html.erb
<div class="row">
  <h1><%= t ".title" %></h1>
  <div class="col-md-8 form-inline filter_form">
    <%= form_tag '', method: :get do %>
      <%= select_tag :category_id, options_from_collection_for_select(
        @categories, :id, :conten, params[:categroy_id]),
        include_blank: t(".select_all"), class: "form-control" %>
      <%= submit_tag t(".btn_search"), class: "btn btn-default" %>
    <% end %>
  </div>
  <div class="col-md-4 filter_form">
    <%= link_to new_admin_word_path, class: "btn btn-info pull-right" do %>
        <span class="glyphicon glyphicon-plus-sign"></span>
        <%= t ".btn_add_word" %>
    <% end %>
  </div>
  <table class="table table-bordered">
    <tr class="first_colum" >
      <th><%= t ".word" %></th>
      <th><%= t ".word_answer" %></th>
      <th><%= t ".category" %></th>
      <th><%= t ".action" %></th>
    </tr>
    <%= render @words %>
  </table>
  <div class="center">
    <%= will_paginate %>
  </div>
</div>

app/views/admin/words/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= t ".title" %></h1>
    <%= render "form" %>
  </div>
</div>