config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "home" => "static_pages#home"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :lessons
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :categories, only: [:index, :show]
  resources :words, only: [:index]
  resources :lessons
  namespace :admin do
    root "users#index"
    resources :users, only: [:destroy, :index, :update]
    resources :words
    resources :categories
  end

end

app/views/shared/_activity.html.erb
<tr>
  <td>
    <div class="activity">
      <span class="activity_content">
        <%= activity.content %>
      </span>
      <div class="timestamp">
        <span class="glyphicon glyphicon-calendar"></span>
        <%= t "time_ago", time: time_ago_in_words(activity.created_at) %>
      </div>
    </div>
  </td>
</tr>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t("error_message") + pluralize(object.errors.count, t("error") )%>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_introduction.html.erb
<section>
  <div class="col-md-8 introduction">
    <h1><%= t "home_title" %></h1>
    <p><%= t "introduction" %></p>
    <div class="btn_signup_introduct center">
      <%= link_to t("signup"), new_user_path, class: "btn btn-info btn-lg" %>
    </div>
  </div>
  <div class="col-md-4">
    <%= image_tag "introduction.jpg", class: "image_introduction" %>
  </div>

</section>

app/views/shared/_stats.html.erb
<div class="stats">
  <% @user ||= current_user %>
  <%= link_to following_user_path @user do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t(".following") %>
  <% end %>
  <%= link_to followers_user_path @user do %>
    <strong id="following" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t(".followers") %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h3><%= current_user.name %></h3>