config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "help"    => "static_pages#help"
  get "about"   => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "home" => "static_pages#home"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :lessons
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :account_activations, only: [:edit]
  resources :categories, only: [:index, :show]
  resources :words, only: [:index]
  resources :lessons
  namespace :admin do
    root "users#index"
    resources :users, only: [:destroy, :index, :update]
    resources :words
    resources :categories
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words
  has_many :lessons

  validates :conten, presence: true, length: {minimum: 3, maximum: 150}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user, :load_category, :verify_admin

  def index
    @categories = Category.paginate page: params[:page],
      per_page: Settings.category.per_page
  end

  def show
    @category = Category.find_by id: params[:id]
    if @category.nil?
      flash[:danger] = t "waring"
      render :index
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "addedcategory"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "admin.success"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "admin.deletecategory"
    else
      flash[:danger] = t ".fail"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
      params.require(:category).permit(:conten)
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_cateogry, only: :show

  def index
    @categories = Category.order(created_at: :desc).paginate page:
      params[:page], per_page: Settings.per_page
  end

  def new
    @category = Category.new
  end

  def show
    @words = @category.words.paginate page: params[:page],
      per_page: Settings.per_page
  end

  private
  def load_cateogry
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:danger] = t ".not found"
      redirect_to categories_url
    end
  end
end

app/views/admin/categories/_category.html.erb
<tr>
  <td class="center"><%= category_counter +1 %></td>
  <td><%= category.conten %></td>
  <td class=" button_action center">
    <%= link_to [:edit, :admin, category], "data-toggle": "tooltip",
      title: t("tooltip_edit") do  %>
      <span class="glyphicon glyphicon-pencil"></span>
    <% end %>

    <%= link_to [:admin, category], "data-toggle": "tooltip",
      title: t("tooltip_delete", name: category.conten), method: :delete do  %>
      <span class="glyphicon glyphicon-trash"></span>
    <% end %>

    <%= link_to new_admin_word_path, "data-toggle": "tooltip",
      title: t("admin.words.index.btn_add_word") do %>
        <span class=" glyphicon glyphicon-plus-sign"></span>
    <% end %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object  %>
  <%= f.label :name %>
  <%= f.text_field :conten, class: "form-control" %>
  <div class="buton_action">
    <%= f.submit class: "my_btn" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="title"><%= t "category" %></h1>
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class="row">
  <h1 class="title"><%= t "category" %></h1>
  <div class="col-md-10 col-md-offset-1 ">
  <div class="filter_form">
    <%= link_to new_admin_category_path, class: "btn btn-info pull-left" do %>
      <span class="glyphicon glyphicon-plus-sign"></span>
      <%= t ".add_category" %>
    <% end %>
    <br>
  </div>
    <table class="table table-bordered">
      <thead>
        <tr class="first_colum">
          <th><%= t ".index" %></th>
          <th><%= t ".content" %></th>
          <th><%= t ".feature" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render @categories %>
      </tbody>
    </table>
    <%= will_paginate %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= t "category" %></h1>
    <%= render "form" %>
  </div>
</div>